name: build python API

on:
  push

jobs:
  use-actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with: 
        python-version: '3.x'
    - name: install dependencies
      run: python -m pip install --upgrade pip
           pip install flask
           pip install flask_cors
           pip install redis
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
    - name: build API
      run: python3 TP/backend/app.py check_syntax
      
    

