name: Example of Action workflow

on:
  workflow_dispatch:

jobs:
  use-actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Weather
      run: curl http://wttr.in/paris
